name: pdf_converter
description: Conversor de imagens para PDF com suporte a mosaico
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.7
  path_provider: ^2.0.15
  pdf: ^3.8.4
  permission_handler: ^10.2.0
  image: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  photo_view: ^0.14.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 